// src/events/eventTypes.ts

export enum EventType {
  // Pricing Engine
  PRICING_GENERATED = "PRICING_GENERATED",
  PRODUCT_PRICING_APPLIED = "PRODUCT_PRICING_APPLIED",
  RISK_TIER_APPLIED = "RISK_TIER_APPLIED",
  FINAL_RATE_CALCULATED = "FINAL_RATE_CALCULATED",
  PRICING_ERROR = "PRICING_ERROR",

  // Underwriting Engine
  UW_SUBMITTED = "UW_SUBMITTED",
  UW_DECISION_ISSUED = "UW_DECISION_ISSUED",
  UW_CONDITIONS_CREATED = "UW_CONDITIONS_CREATED",
  UW_CONDITION_SATISFIED = "UW_CONDITION_SATISFIED",
  UW_FINAL_APPROVAL = "UW_FINAL_APPROVAL",
  UW_ERROR = "UW_ERROR",

  // Appraisal Service
  APPRAISAL_ORDERED = "APPRAISAL_ORDERED",
  APPRAISAL_RECEIVED = "APPRAISAL_RECEIVED",
  APPRAISAL_EVALUATED = "APPRAISAL_EVALUATED",
  COLLATERAL_RISK_ASSIGNED = "COLLATERAL_RISK_ASSIGNED",

  // Insurance Service
  INSURANCE_QUOTE_RECEIVED = "INSURANCE_QUOTE_RECEIVED",
  INSURANCE_POLICY_SELECTED = "INSURANCE_POLICY_SELECTED",
  REPLACEMENT_COST_VALIDATED = "REPLACEMENT_COST_VALIDATED",

  // Title Service
  TITLE_ORDERED = "TITLE_ORDERED",
  TITLE_COMMITMENT_RECEIVED = "TITLE_COMMITMENT_RECEIVED",
  TITLE_LIENS_VALIDATED = "TITLE_LIENS_VALIDATED",

  // Rate Lock Engine
  RATE_LOCK_CREATED = "RATE_LOCK_CREATED",
  RATE_LOCK_VALIDATED = "RATE_LOCK_VALIDATED",
  RATE_LOCK_EXPIRED = "RATE_LOCK_EXPIRED",

  // Closing Engine
  COMMITMENT_LETTER_ISSUED = "COMMITMENT_LETTER_ISSUED",
  CLOSING_DISCLOSURE_ISSUED = "CLOSING_DISCLOSURE_ISSUED",
  CLOSING_PACKAGE_GENERATED = "CLOSING_PACKAGE_GENERATED",
  E_SIGN_COMPLETED = "E_SIGN_COMPLETED",
  FUNDED = "FUNDED",

  // Investor Delivery Engine
  DELIVERY_PACKAGE_CREATED = "DELIVERY_PACKAGE_CREATED",
  LOAN_SOLD = "LOAN_SOLD",
  BOARDING_COMPLETE = "BOARDING_COMPLETE",

  // Blockchain Anchoring
  MERKLE_SNAPSHOT_CREATED = "MERKLE_SNAPSHOT_CREATED",
  ANCHOR_TX_MINED = "ANCHOR_TX_MINED"
}
